### ISSUE TITLE
failed to find digital objects via SPARQL

### ISSUE THREAD

**Issue by fdiehr** [funkyfuture/m4p0-rs-metadata-import#10]
um Digitale Objekte anzuzeigen, muss ein Template generiert werden. Das Template enthält eine SPARQL query, die alle Statements zu D1.Digital_Objects abfragt.
Das Template: https://researchspace.curving.space/resource/?uri=Template%3Ahttp%3A%2F%2Fwww.ics.forth.gr%2Fisl%2Frdfs%2F3D-COFORM_CRMdig.rdfs%23D1.Digital_Object
Die Query:

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX m4p0: <https://www.museum4punkt0.de/catalogue/ontology/>
PREFIX crmdig: <http://www.ics.forth.gr/isl/CRMdig/>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?name ?provider ?mediatype ?creation ?rights ?license ?licensor ?musobj ?site WHERE {
                ?s a crmdig:D1.Digital_Object;
               			m4p0:fileName ?name;
    								edm:dataProvider ?provider ;
    								m4p0:hasMediaType ?mediatype ;
    								crm:P94i_was_created_by ?creation.
                    
   OPTIONAL { ?s a crmdig:D1.Digital_Object;
                 dc:rights ?rights}
  OPTIONAL {?s a crmdig:D1.Digital_Object;
               dcterms:license ?license }
  OPTIONAL {?s a crmdig:D1.Digital_Object;
               m4p0:licensor ?licensor }
  OPTIONAL {?s a crmdig:D1.Digital_Object;
               m4p0:refersToMuseumObject ?musobj }
  OPTIONAL {?s a crmdig:D1.Digital_Object;
edm:shownAt ?site .}                
            }

Auch wenn ich die Query im SPARQL Endpoint ausführe, bekomme ich keine Ergebnisse.

Ich  wollte mich dann nach und nach herantasten, in dem ich nur Teile der Query ausführe, wie z.B. 

SELECT  *  WHERE {
                ?s a crmdig:D1.Digital_Object;
edm:dataProvider ?provider 
            }

aber auch das findet nix.
Wenn ich hingegen ein konkretes subject habe, dann funktionert es:

SELECT * WHERE {
  <https://objekte.museum4punkt0.de/narrenschopf/C%201.1.2.14-5-001.tif> edm:dataProvider ?o }
provider = http://www.vsan.de/

Was ist da los?

**Comment by fdiehr** [comment]
Okay, leider gibt es weiterhin ein problem mit dem import bzw. damit, dass abfragen statements nicht finden, obwohl sie da sind. 
wenn man sich die statements für den graph <https://enter.museum4punkt0.de/resource/132b1306-177f-5adf-a8bf-bd65db80f597> ansieht, dann werden alle statements angezeigt:
<img width="1393" alt="Bildschirmfoto 2020-01-22 um 17 03 50" src="https://user-images.githubusercontent.com/26928727/72910695-2fa51680-3d39-11ea-94d9-a5d11d819594.png">

wenn ich nun aber über den SPARQL endpoint einzelne statements suche werden manche gefunden, andere nicht. wie kann das sein?

FAILED:
`SELECT * WHERE { ?s m4p0:hasMediaType ?o.}`

SUCCESS:
`SELECT * WHERE { ?s edm:dataProvider ?o.}`

**Comment by fdiehr** [comment]
japp, prefix ist falsch.
SUCCESS:
`SELECT * WHERE { ?s <https://enter.museum4punkt0.de/ontology/refersToMuseumObject> ?o}`

**Comment by funkyfuture** [comment]
solved with #16, right? i'll update the dataset later this evening.
