### ISSUE TITLE
kodierungsfehler im json

### ISSUE THREAD

**Issue by fdiehr** [funkyfuture/m4p0-rs-metadata-import#18]
hey, ich hab nochmal in das json geguckt und es gibt immer noch kodierungsfehler wie:
Strohb\u00e4r

**Comment by funkyfuture** [comment]
das müsste nach meinem wissen korrekt sein, weil json immer eine bytesequenz ist und kein unicode. und das erzeugt auch einen unicode-string mit der JS-vm im browser:

```js
var json = '{"result":"Strohb\u00e4r"}';
var obj = JSON.parse(json)
console.log(obj)
```

```
Object { result: "Strohbär" }
```

**Comment by fdiehr** [comment]
öh, okay. komisch. warum seh ich das denn aber im browser? guck mal hier: [](https://researchspace.curving.space/resource/?uri=Template%3Ahttps%3A%2F%2Fwww.museum4punkt0.de%2Fcatalogue%2Fontology%2FMuseumObject)

**Comment by funkyfuture** [comment]
na, weil das eben noch nicht geparsed ist. es ist an der stelle nur eine (nicht-unicode-)zeichenkette.

**Comment by fdiehr** [comment]
okay, versteh ich aber noch nicht ganz: wann wird das geparst? beim upload? (und deswegen ist das jetzt noch nicht zu sehen, weil es noch der alte upload ist?)

**Comment by funkyfuture** [comment]
> wann wird das geparst?

das muss eine anwendung machen (im browser mit `JSON.parse`), dazu ist es ja gedacht. json ist ein austauschformat, nix was zur anzeige gedacht ist.

ich hab mal noch ein bißchen rumgelesen. es ist wohl so, dass json auch als unicode kodiert sein könnte, encoder-implementierungen das zur gewährleistung von kompatibilität aber meist sein lassen. ich hab auch probiert was passiert, wenn man bei der python-stdlib-implementierung das `ensure_ascii`-argument auf `False` setzt, da kommt das genauso raus.

**Comment by funkyfuture** [comment]
vorschlag: ergänze doch einfach die überschrift, ungefähr so: `Kataloginformationen (JSON)`, dann steht genauer drüber was oder vielmher wi es ist.

kannst du zufällig den ganzen code der react-komponente, die da benutzt wird, bereit stellen? dann könnte ich, falls ich shcnell damit klar kommen sollte, schauen, dass die tabelle entspechend dem json expandiert wird.

**Comment by fdiehr** [comment]
ah okay, dacht e mir, dass es durch den browser gemacht wird, hatte mich dann nur gewundert, dass es chrome nicht macht. 

> vorschlag: ergänze doch einfach die überschrift, ungefähr so: Kataloginformationen (JSON), dann steht genauer drüber was oder vielmehr wi es ist.

ja, kan ich machen versteht nur keiner von "meinen" anwendern. kann mir dann aber auch egal sein ;)

> kannst du zufällig den ganzen code der react-komponente

 guck mal hier: https://researchspace.curving.space/resource/Help:SemanticTable 
nutzt das was?
hey, aber wenn das jetzt zu aufwändig ist, dann ist das auch okay. kein problem. dann lassen wir das einfach so, wie es ist.

**Comment by funkyfuture** [comment]
> hatte mich dann nur gewundert, dass es chrome nicht macht.

auch die JS engine in Chrome macht das, aber nicht der html-renderer. der verarbeitet html, nicht json.

>  wenn das jetzt zu aufwändig is

ich denke ja.
