### ISSUE TITLE
Testimport: Fehler

### ISSUE THREAD

**Issue by fdiehr** [funkyfuture/m4p0-rs-metadata-import#8]
1. Typo: `MuseumObjectTtile` und da es eine property ist, bitte klein schreiben: museumObjectTitle
2. Kodierungsfehler bei Umlauten etc. (deutsche Buchstaben): Ã¼ber (=über)
3. rdf:Object von P94i_was_created_by: Hier sind offensichtliche mehrere Einträge zu einem rdf:Object geworden: `http://www.vsan.de/ / https://objekte.museum4punkt0.de/narrenschopf/ / https://www.iana.org/assignments/media-types/image/tiff` 
als Object muss hier eigentlich die Klasse crm:E65_Creation kommen.  Bin mir nicht sicher, was du hier mit den Eingaben für ein Statement machen wolltest. Laut der Specification muss hier eigentlich folgendes kommen: `digital_app_creation <- crm:E65_Creation-instanz via m4p0:hasCreatedDigitalApp von {digital_app} (optional)` (Zeile 101-102)

**Comment by fdiehr** [comment]
> die idee, das label dort hinzuzufügen war, dass editierende, die daten zu diesen creations erfassen, ne orientierung haben, um welche es sich konkret handelt, via bezug über die resultate.

hmm verstehe.  alle anderen creations haben aber kein label, dann find ich das ungünstig, wenn nur diese eines bekommen. und es ist auch etwas hässlich aus sicht der wissensrepräsentation.
ich denke, die zuordnung wird auch anders möglich sein: der hauptanker dafür ist der bezug zum digital object. über das bekommen sie die dazugehörige creation aufgelistet. auch über den data provider wäre das möglich. 
hinzukommt, dass ich antizipieren, dass sie im nachgang die creations nicht nochmal manuell bearbeiten werden deswegen hätte ich gern die angabe von "hasCreationPhase" und "hasCreationMethod" direkt gespeichert. 

> es fällt mir sehr schwer den erörterungen hier zu folgen. ist alles diesbezügliche in #13 enthalten?

ja, die sind eigentlich in der spec drin. aber ich verstehe, dass es schwierig zu verstehen ist, wenn man nicht so tief in der datenstruktur drin steckt. deswegen dachte ich kurz treffen, weil kann man besser erklären. ich kann das aber auch mal versuchen aufzumalen und dir dann schicken.

**Comment by fdiehr** [comment]
> über das bekommen sie die dazugehörige creation aufgelistet.
 btw... wie ist das jetzt? wird eine creation pro import erzeugt (also n + 1 digital object hat 1 creation) oder hat jedes digital object seine "eigene" creation?
ersteres wäre zu bevorzugen, da sonst sinnlos viele creations entstehen würden.
aus der spec würde ich aber 2. verstehen.

**Comment by funkyfuture** [comment]
> btw... wie ist das jetzt?

je datenset und den darin enthaltenen distinkten media type wird eine creation angelegt.

ich schließe das jetzt hier, weil ich denke, dass ein aktiver ort zur diskussion von zusammengehörendem nachvollziehbarer und verlässlicher ist. das sollte im augenblick an der änderung der spezifikation erfolgen.

**Comment by fdiehr** [comment]
> je datenset und den darin enthaltenen distinkten media type wird eine creation angelegt.

ja, perfekt! 

> ich schließe das jetzt hier,

yo, alles klar!
